# Generated by Django 6.0.6 on 2026-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor_slug', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(choices=[('none', 'Not connected'), ('google', 'Google Calendar'), ('outlook', 'Outlook')], default='none', max_length=16)),
                ('is_connected', models.BooleanField(default=False)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_calendar_id', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor_slug', models.CharField(db_index=True, max_length=64)),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in-person', 'In person')], max_length=16)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('calendar_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('counsellor_slug', 'start_at'), name='unique_confirmed_slot_per_counsellor')],
            },
        ),
    ]
