# Generated by Django 6.0.6 on 2026-07-19 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('eyebrow', models.CharField(max_length=80)),
                ('intro', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('credentials', models.CharField(max_length=160)),
                ('photo', models.ImageField(blank=True, upload_to='counsellors/')),
                ('photo_placeholder', models.CharField(blank=True, default='images/face_1.png', max_length=200)),
                ('location', models.CharField(max_length=120)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('modes', models.JSONField(blank=True, default=list)),
                ('intro', models.TextField()),
                ('bio', models.TextField()),
                ('modalities', models.JSONField(blank=True, default=list)),
                ('fee_note', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.servicecategory')),
            ],
            options={
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CounsellorWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_blocks', to='core.counsellor')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('counsellor', 'weekday', 'start_time'), name='unique_counsellor_weekday_start')],
            },
        ),
        migrations.CreateModel(
            name='CounsellorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(2, 'Primary'), (1, 'Secondary')])),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_links', to='core.counsellor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('counsellor', 'topic'), name='unique_counsellor_topic')],
            },
        ),
    ]
