# Generated by Django 6.0.6 on 2026-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_service_and_counsellor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
